name: "Update GitOps Repo"
description: "Update the GitOps repository"
inputs:
  image_name:
    description: "The Docker image name to be used"
    required: true

  image_tag:
    description: "The Docker image tag to be used"
    required: true

  gitops_repo_name:
    description: "The GitOps repository name"
    required: true

  git_commit_user:
    description: "The user that will be used for the git commit"

    default: "gitops bot"
  gitops_repo_owner:
    description: "The owner of the GitOps repo"
    required: true

  file_path_dev:
    description: 'The file path for development environment where sed will replace'
    required: true

  file_path_prod:
    description: 'The file path for production environment where sed will replace'
    required: true

  github_app_private_key:
    required: true
  github_app_id:
    required: true

runs:
  using: "composite"
  steps:
    - name: Create GitHub App Token
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ inputs.github_app_id }}
        private-key: ${{ inputs.github_app_private_key }}
        owner: ${{ inputs.gitops_repo_owner }}
        repositories: ${{ inputs.gitops_repo_name }}

    - name: Checkout GitOps Repo
      uses: actions/checkout@v4
      with:
        token: ${{ steps.app-token.outputs.token }}
        ref: ${{ github.head_ref }}
        persist-credentials: false
        repository: ${{ inputs.gitops_repo_owner }}/${{ inputs.gitops_repo_name }}
        path: gitops-repo


    - name: Update GitOps Repo
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      shell: bash
      run: |
        cd gitops-repo
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          FILE_PATH=${{ inputs.file_path_dev }}
        elif [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
          FILE_PATH=${{ inputs.file_path_prod }}
        else
          echo "No matching condition for the current ref: ${GITHUB_REF}"
          exit 1
        fi
        
        sed -i "s;:${{ inputs.image_name }}_.*$;:${{ inputs.image_name }}_${{ inputs.image_tag }};g" $FILE_PATH
        git config user.email "${{ inputs.git_commit_user }}"
        git config user.name "${{ inputs.git_commit_user }}"
        git commit -am "Repo: ${{ github.repository }} BumpImageTag: ${{ inputs.image_tag }} Message: ${{ github.event.head_commit.message }}"
        git push https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ inputs.gitops_repo_owner }}/${{ inputs.gitops_repo_name }}.git
