name: "Docker Build/Push and Gitops Update"
description: "Build Docker image with Kaniko and update GitOps repository"
inputs:
  image_name:
    description: "The Docker image name to be used"
    required: true
    
  image_tag:
    description: "The Docker image tag to be used"
    required: true
    
  docker_registry_user:
    description: "The user that will be used for the docker registry"
    required: true
    
  docker_registry:
    description: "The registry that will be used for the docker image"
    
    default: "docker.io"
  docker_registry_password:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Base Image
      uses: aevea/action-kaniko@master
      with:
        build_file: Dockerfile
        registry: ${{ inputs.docker_registry }}
        username: ${{ inputs.docker_registry_user }}
        password: ${{ inputs.docker_registry_password }}
        image: ${{ inputs.image_name }}
        tag: ${{ inputs.image_tag }}
        cache: true
        cache_registry:  ${{ inputs.docker_registry_user }}/cache
